framework:
    cache:
        prefix_seed: aledefreitas/wrt_app
        app: app.cache.adapter

services:
    App\Foundation\Cache\Contracts\CacheConfigInterface:
        factory: [ '@App\Foundation\Cache\CacheConfigFactory', 'createConfig' ]
        arguments:
            - cache-host: '%env(string:KEYDB_CACHE_HOST)%'
              cache-port: '%env(string:KEYDB_CACHE_PORT)%'
              cache-secret: '%env(urlencode:string:KEYDB_CACHE_SECRET)%'
              cache-unix-socket: '%env(string:KEYDB_CACHE_UNIXSOCKET)%'
              cache-default-ttl: '%env(int:KEYDB_CACHE_TTL)%'

    app.cache.adapter.factory:
        class: 'App\Foundation\Cache\Adapter\CacheAdapterFactory'

    app.cache.adapter:
        class: 'App\Foundation\Cache\Contracts\Adapter\CacheAdapterFactoryInterface'
        factory: [ '@app.cache.adapter.factory', 'createAdapter' ]
        arguments:
            - 'namespace'
            - '@App\Foundation\Cache\Contracts\CacheConfigInterface'

when@test:
    services:
        app.cache.adapter.factory:
            class: 'App\Foundation\Testing\Cache\Adapter\CacheAdapterFactory'
