parameters:
    app.db.host: 'localhost'
    app.db.port: 5432
    app.db.user: 'wrt'
    app.db.password: 'changeme'
    app.db.dbname: 'wow_recruitment'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: '%env(resolve:default:app.db.dbname:string:POSTGRE_DATABASE_DB)%'
                host: '%env(resolve:default:app.db.host:string:POSTGRE_DATABASE_CONNECTION_POOL_HOST)%'
                port: '%env(resolve:default:app.db.port:string:POSTGRE_DATABASE_CONNECTION_POOL_PORT)%'
                user: '%env(resolve:default:app.db.user:string:POSTGRE_DATABASE_USER)%'
                password: '%env(resolve:default:app.db.password:string:POSTGRE_DATABASE_PASSWORD)%'
                driver: pdo_pgsql
                server_version: '16.3'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Api\Users:
                type: xml
                dir: '%kernel.project_dir%/src/Api/Users/Infrastructure/Doctrine/Orm/Mappings'
                prefix: App\Api\Users\Domain\Entity

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
