services:
  wrt_mongodb:
    ports:
      - 27017:27017
  wrt_keydb:
    ports:
      - 6379:6379
  wrt_app:
    volumes:
      - ./:/app
      - ./.docker/app/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:80