services:
  wrt_pgbouncer:
    ports:
      - ${POSTGRE_DATABASE_CONNECTION_POOL_PORT:-5432}:5432
  wrt_mongodb:
    ports:
      - ${MONGODB_DATABASE_PORT:-27017}:27017
  wrt_keydb:
    ports:
      - ${KEYDB_CACHE_PORT:-6379}:6379
  wrt_app:
    volumes:
      - ./:/app
      - ./.docker/app/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:80