volumes:
  wrt_pgsql_data:
    driver: local
  wrt_mongodb_data:
    driver: local
  wrt_elasticsearch_data:
    driver: local
  wrt_unix_sockets:
    driver: local

networks:
  wrt_internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.63.0/24

services:
  wrt_keydb:
    container_name: wrt_keydb
    user: "${UID:-1000}:${GID:-1000}"
    # alpine docker images are currently experimental, and KeyDB still requires a bit of work to fully support Alpine Builds
    # @see https://hub.docker.com/r/eqalpha/keydb
    image: 'eqalpha/keydb:x86_64_v6.3.3'
    restart: unless-stopped
    command: ['keydb-server', '/usr/local/etc/keydb/keydb.conf', '--requirepass ${KEYDB_CACHE_SECRET:-changeme}']
    logging:
        options:
            max-size: "20m"
            max-file: "5"
    environment:
      - KEYDB_CACHE_SECRET="${KEYDB_CACHE_SECRET:-changeme}"
    ports:
      - '${KEYDB_CACHE_PORT:-6379}:6379'
    volumes:
      - './.docker/keydb/keydb.conf:/usr/local/etc/keydb/keydb.conf'
      - 'wrt_unix_sockets:/tmp/'
    networks:
      - wrt_internal_network

  # WoW Recruitment App
  wrt_app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
      target: ${ENV:-prod}
      args:
          UID: ${UID:-1000}
          GID: ${GID:-1000}
    restart: unless-stopped
    env_file: ./.env
    container_name: wrt_app
    volumes:
      - ./.docker/app/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./.docker/app/supervisor/conf.d:/etc/supervisor/conf.d
      - ./.docker/app/php/fpm/www-common.conf:/usr/local/etc/php-fpm.d/www-common.conf
      - ./.docker/app/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/app/php/config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./logs:/app/logs
      - wrt_unix_sockets:/var/run/sockets/
    networks:
      - wrt_internal_network
