volumes:
  wrt_kibana_data:
    driver: local

services:
  # Merge services in docker-compose.yml to overwrite settings
  wrt_elasticsearch:
    ports:
      - ${ELASTICSEARCH_PORT:-9200}:9200
  wrt_pgbouncer:
    ports:
      - ${POSTGRE_DATABASE_CONNECTION_POOL_PORT:-5432}:5432
  wrt_mongodb:
    ports:
      - ${MONGODB_DATABASE_PORT:-27017}:27017
  wrt_keydb:
    ports:
      - ${KEYDB_CACHE_PORT:-6379}:6379
  wrt_app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - ./.docker/app/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:8080
  # Add extra services for dev-only
  # Mongo Express
  wrt_mongo_express:
    image: mongo-express:1.0.2
    container_name: wrt_mongo_express
    depends_on:
      wrt_mongodb:
        condition: service_healthy
    links:
      - wrt_mongodb
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_DATABASE_HOST}:${MONGODB_DATABASE_PORT}
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_DATABASE_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_DATABASE_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_DATABASE_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    networks:
      - wrt_internal_network
    ports:
      - 8081:8081
  # Kibana
  wrt_kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: wrt_kibana
    depends_on:
      wrt_elasticsearch:
        condition: service_healthy
    links:
      - wrt_elasticsearch
    volumes:
      - ./.docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - wrt_kibana_data:/usr/share/kibana/data
    environment:
      - "ELASTICSEARCH_URL=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=OYVOul44mbmVYa2ZvxBEVoXffawn6XbG
      - xpack.security.enabled=false
    networks:
      - wrt_internal_network
    ports:
      - 5601:5601
