parameters:
    app.version: '1.0.0'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Infrastructure/DependencyInjection/'
            - '../src/*/Domain/Entity'
            - '../src/Kernel.php'

    App\Api\Shared\Infrastructure\Http\Controller\:
        resource: ../src/Api/Shared/Infrastructure/Http/Controller/
        tags: ['controller.service_arguments']

    App\Api\Users\Infrastructure\Http\Controller\:
        resource: ../src/Api/Users/Infrastructure/Http/Controller/
        tags: ['controller.service_arguments']
